environments:
    - dev
    - staging
    - training
    - hotfix
    - prod

# this maps environment names to vpc & aws accounts
vpc-environment-map:
    "*":
        vpc: intranet-nonprod
        aws_account: intranet
    prod:
        vpc: intranet-prod
        aws_account: intranet-prod
    hotfix:
        vpc: intranet-hotfix
        aws_account: intranet-prod
