repos:
  - repo: local
    hooks:
      - id: terraform-fmt
        name: Format Terraform code
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false
  - repo: local
    hooks:
      - id: tflint
        name: Lint Terraform code
        entry: tflint --recursive --fix
        language: system
        pass_filenames: false
#  - repo: local
#    hooks:
#      - id: trufflehog
#        name: TruffleHog
#        description: Detect secrets in your data.
#        entry: bash -c 'trufflehog filesystem . --no-verification --fail --exclude-paths=.trufflehogignore'
#        language: system
#        stages: ["commit", "push"]
