repos:
  - repo: local
    hooks:
      - id: terraform-fmt
        name: Format Terraform code
        entry: terraform fmt -recursive
        language: system
        pass_filenames: false
  # Todo: Address the results of `tflint --recursive` before enabling this...
  # - repo: local
  #   hooks:
  #     - id: tflint
  #       name: Lint Terraform code
  #       entry: tflint --recursive --fix
  #       language: system
  #       pass_filenames: false
