# Example AWS Access Key:
fake_access_key1: "AKIAIOSFODNN7EXAMPLE"
fake_access_key2: "ASIAI44QH8DHBEXAMPLE"
fake_access_key3: "ACCAJODIBQYJ5EXAMPLE"
fake_access_key4: "AGPARFODNN7EJANQW3AMPLE"
fake_access_key5: "AIDAJ2GBU5Q25EXAMPLE"
# Example AWS Secret Access Key:
fake_secret_key1: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
fake_secret_key2: "HMACDENC7QEXAMPLEDASQOWXW+4JwXs7x47EXAMPLEKEY"
fake_secret_key3: "MCDHFSUZ5EXAMPLEWFVEMDIUMJ8US/ExYGH6yXyfYEXAMPLEKEY"
fake_secret_key4: "T3SFEMC7EXAMPLE9W2kG9cpC1y5TWhVU/+2X5wEXAMPLEKEY"
fake_secret_key5: "T3SFEMC7EXAMPLE9W2kG9cpC1y5TWhVU/+2X5w+EXAMPLEKEY"