version: 0.2

env:
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token
  variables:
    TERRAFORM_VERSION: 1.8.1
  exported-variables:
    - SLACK_REF

phases:
  install:
    commands:
      - set -e
      - echo "Deploying ${APPLICATION} environments"
      - VERSION_OUTPUT=""
      - |
        if [ ! -f .platform-helper-version ]; then
          echo "Cannot find .platform-helper-version file"
          exit 1
        fi
      - PLATFORM_HELPER_VERSION=`cat .platform-helper-version`
      - echo "Installing build tools"
      - yum -y install python-pip
      - mkdir ./build-tools
      - cd ./build-tools
      - pip install --target . --quiet dbt-platform-helper==$PLATFORM_HELPER_VERSION
      - export "PATH=$(pwd)/bin:$PATH"
      - export PYTHONPATH=$(pwd)
      - | 
          if [ "${SLACK_THREAD_ID}" == "NONE" ]
          then
            export SLACK_REF=$(platform-helper notify environment-progress "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" \
            "*Deploying ${APPLICATION} environments*" \
            --build-arn "${CODEBUILD_BUILD_ARN}" \
            --repository "${REPOSITORY}" \
            --commit-sha "${CODEBUILD_RESOLVED_SOURCE_VERSION: -7}")
          else
            export SLACK_REF="${SLACK_THREAD_ID}"
          fi
      - cd bin
      - curl -s -qL -o terraform_install.zip https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
      - unzip terraform_install.zip
      - chmod +x terraform
      - rm terraform_install.zip
      - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Starting install phase"
      - VERSION_OUTPUT+="\n$(terraform --version)"
      - VERSION_OUTPUT+="\n$(platform-helper --version)"
      - VERSION_OUTPUT+="\n$(python3 --version)"
      - VERSION_OUTPUT+="\n$(pip --version)"
      - echo -e "=============\nTool Versions\n-------------\n$VERSION_OUTPUT"
      - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Install phase complete"
artifacts:
  files:
    - "**/*"
