version: 0.2

env:
  parameter-store:
    SLACK_CHANNEL_ID: /codebuild/slack_pipeline_notifications_test_oauth_channel
    SLACK_TOKEN: /codebuild/slack_oauth_token
  exported-variables:
    - BUILD_ID

phases:
  install:
    commands:
      - export PATH="${CODEBUILD_SRC_DIR}/build-tools/bin:$PATH"
      - export PYTHONPATH="${CODEBUILD_SRC_DIR}/build-tools"
  build:
    commands:
      - set -e
      - echo "Terraform Plan Phase"
      - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Starting terraform plan phase for the ${ENVIRONMENT} environment."
      - echo "Working on environment ${ENVIRONMENT}"
      - echo "Generating manifests"
      - copilot env init --name ${ENVIRONMENT} --profile ${COPILOT_PROFILE} --default-config
      - platform-helper copilot make-addons
      - cd terraform/environments/${ENVIRONMENT}
      - terraform init
      - terraform plan -out=plan.tfplan
  post_build:
    commands:
      - export BUILD_ID="$CODEBUILD_BUILD_ID"
      - |
        if [ "${CODEBUILD_BUILD_SUCCEEDING}" == "1" ]
        then
          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Terraform plan phase complete for the ${ENVIRONMENT} environment."
          if [ "${NEEDS_APPROVAL}" == "yes" ]
          then
            platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Waiting for approval for the ${ENVIRONMENT} environment."
          fi
        else
          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Terraform plan phase FAILED for the ${ENVIRONMENT} environment."
        fi
artifacts:
  files:
    - terraform/environments/${ENVIRONMENT}/plan.tfplan
