version: 0.2

env:
  parameter-store:
    SLACK_TOKEN: /codebuild/slack_oauth_token
  exported-variables:
    - BUILD_ID

phases:
  install:
    commands:
      - export PATH="${CODEBUILD_SRC_DIR}/build-tools/bin:$PATH"
      - export PYTHONPATH="${CODEBUILD_SRC_DIR}/build-tools"
  build:
    commands:
      - set -e
      - echo "Terraform Plan Phase"
      - platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Starting terraform plan phase for the ${ENVIRONMENT} environment."
      - echo "Working on environment ${ENVIRONMENT}"
      - |
        ADDITIONAL_OPTIONS=
        if [ ! -z "${TERRAFORM_PLATFORM_MODULES_VERSION}" ]
        then 
          $ADDITIONAL_OPTIONS+=" --terraform-platform-modules-version ${TERRAFORM_PLATFORM_MODULES_VERSION}"
        fi
        if [ "${APPLICATION}" == "demodjango" ] && [ "${ENVIRONMENT}" == "toolspr" ]; then
          echo "Skipping platform-helper environment generate-terraform for demodjango toolspr environment until we can make it use terraform-platform-modules main branch"
        else
          platform-helper environment generate-terraform --name "${ENVIRONMENT}" "${ADDITIONAL_OPTIONS}"
        fi
      - cd terraform/environments/${ENVIRONMENT}
      - terraform init
      - terraform plan -out=plan.tfplan
  post_build:
    commands:
      - export BUILD_ID="$CODEBUILD_BUILD_ID"
      - |
        if [ "${CODEBUILD_BUILD_SUCCEEDING}" == "1" ]
        then
          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Terraform plan phase complete for the ${ENVIRONMENT} environment."
          if [ "${NEEDS_APPROVAL}" == "yes" ]
          then
            platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Waiting for approval for the ${ENVIRONMENT} environment."
          fi
        else
          platform-helper notify add-comment "${SLACK_CHANNEL_ID}" "${SLACK_TOKEN}" "${SLACK_REF}" "Terraform plan phase FAILED for the ${ENVIRONMENT} environment."
        fi
artifacts:
  files:
    - "**/*"
