version: 0.2
phases:
  install:
    commands:
      - export PATH="$CODEBUILD_SRC_DIR/build-tools:$PATH"
      - platform_helper.py --version
      - terraform --version
      - copilot --version
  build:
    commands:
      - echo "Terraform Plan Phase"
      - echo "Working on environment ${ENVIRONMENT}"
      - cd terraform/${ENVIRONMENT}
      - terraform init
      - terraform plan -out=plan.tfplan
artifacts:
  files:
    - terraform/${ENVIRONMENT}/plan.tfplan
