version: 0.2

env:
  parameter-store:
    SLACK_CHANNEL_ID: /codebuild/slack_pipeline_notifications_test_oauth_channel
    SLACK_TOKEN: /codebuild/slack_oauth_token

phases:
  install:
    commands:
      - export PATH="$CODEBUILD_SRC_DIR/build-tools:$PATH"
      - mv $CODEBUILD_SRC_DIR_terraform_plan/terraform/environments/${ENVIRONMENT}/plan.tfplan $CODEBUILD_SRC_DIR/terraform/environments/${ENVIRONMENT}/
  build:
    commands:
      - echo "Terraform Apply Phase"
      - env
      - echo "Working on environment ${ENVIRONMENT}"
      - cd terraform/environments/${ENVIRONMENT}
      - terraform init
      - terraform apply plan.tfplan
  post_build:
    commands:
      - copilot env deploy --name ${ENVIRONMENT}
artifacts:
  files: []
