---
plan:
  name: "Plan"
  category: "Build"
  owner: "AWS"
  provider: "CodeBuild"
  input_artifacts: ["project_deployment_source"]
  output_artifacts: ["build_output"]
  version: "1"

approve:
  name: "Approval"
  category: "Approval"
  owner: "AWS"
  provider: "Manual"
  version: "1"
  input_artifacts: []
  output_artifacts: []

apply:
  name: "Apply"
  category: "Build"
  owner: "AWS"
  provider: "CodeBuild"
  input_artifacts: ["project_deployment_source"]
  output_artifacts: ["build_output"]
  version: "1"
