services:
  manage-users:
    networks:
      - testnet
    build:
      context: ../manage-users
    depends_on:
      - postgres-unittest
    ports:
      - '9004:8080'
    environment:
      DATABASE_URL: postgres://test_user:test_pw@postgres-unittest:5432/test_db
    volumes:
      - ./:/src

  postgres-unittest:
    networks:
      - testnet
    image: postgres:13
    restart: always
    command: 'postgres -c log_statement=all -c fsync=off -c vm.zone_reclaim_mode=0 -c synchronous_commit=off -c checkpoint_completion_target=0.9 -c random_page_cost=1.1'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_pw

networks:
  testnet:
    driver: bridge