name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: release-config.json
          manifest-file: release-manifest.json
      - name: tag major and minor versions
        if: ${{ steps.release.outputs.release_created }}
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git remote add gh-token "https://${{ secrets.GITHUB_TOKEN }}@github.com/google-github-actions/release-please-action.git"
          git tag -d ${{ steps.release.outputs.major }} || true
          git tag -d ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git push origin :${{ steps.release.outputs.major }} || true
          git push origin :${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} || true
          git tag -a ${{ steps.release.outputs.major }} -m "Release v${{ steps.release.outputs.major }}"
          git tag -a ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }} -m "Release v${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}"
          git push origin ${{ steps.release.outputs.major }}
          git push origin ${{ steps.release.outputs.major }}.${{ steps.release.outputs.minor }}
