name: "Lint PR"

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize

permissions:
  pull-requests: read

jobs:
  main:
    name: Validate pull request title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  tests:
    name: Test against Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    env:
      AWS_REGION: eu-west-2
      AWS_DEFAULT_REGION: eu-west-2

    strategy:
      matrix:
        python-version: ["3.12", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python --version

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install

      - name: Run pytest
        run: poetry run pytest
        env:
          PYTHON_VERSION: ${{ matrix.python-version }}