name: Terraform Unit Tests

on:
  push:
  # Todo: Add a nightly run

jobs:
  application-load-balancer-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - run: |
          cd application-load-balancer
          terraform init
      - run: |
          cd application-load-balancer
          terraform test
