name: Terraform Unit Tests

on:
  push:
  schedule:
    - cron: '30 5 * * *'

permissions: read-all

env:
  AWS_REGION: eu-west-2
  AWS_PROFILE: platform-sandbox

jobs:
  find-modules-to-test:
    runs-on: ubuntu-latest

    outputs:
      modules: ${{ steps.find-modules.outputs.modules }}

    steps:
      - uses: actions/checkout@v4
      - name: Find modules
        id: find-modules
        run: |
          unit_test_files=$(find . -name "*tftest.hcl" | grep -v e2e-tests | sort)
          modules=""
          IFS=$'\n'
          for file in $unit_test_files
          do
            # Lose leading ./ and select the part before the tests directory
            module=$(echo "${file#./}" | awk -F "/tests/" '{print $1}')
            # In case we separate the test files, only include each module once
            if [[ "\"${modules}\"" != *"\"${module}\""* ]]; then
              echo "Found module ${module}"
              modules+="\"${module}\","
            fi
          done
          echo "modules=[${modules%,}]" >> "$GITHUB_OUTPUT"

  terraform-unit-tests:
    name: ${{ matrix.module }} tf-${{ matrix.terraform-version }}
    runs-on: ubuntu-latest
    needs: find-modules-to-test
    strategy:
      matrix:
        terraform-version:
          - 1.8
          - 1.9
        module: ${{ fromJSON(needs.find-modules-to-test.outputs.modules) }}
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform-version }}
      - run: terraform --version
      - name: Set AWS Environment
        run: |
          aws configure set region $AWS_REGION
          export AWS_PROFILE=$AWS_PROFILE
      - name: terraform init
        run: |
          cd ${{ matrix.module }}
          terraform init
      - name: Check AWS Profile
        run: |
          echo "AWS_PROFILE is set to: $AWS_PROFILE"
      - name: Debug Environment
        run: env
      - name: Test AWS CLI
        run: aws --version
      - name: Check AWS Region
        run: |
          echo "AWS REFGION: $AWS_REGION"
      # - name: Debug AWS Authentication
      #   run: |
      #     aws configure list 
      #     aws configure list-profiles 
      #     echo "Current AWS Profile: $AWS_PROFILE" 
      #     echo "Current AWS Region: $AWS_REGION"
      - name: terraform test
        run: |
          cd ${{ matrix.module }}
          terraform test
